### ISSUE TITLE
Negative chi^2 value from llratio()

### ISSUE THREAD

**Issue by sjewo** [depmix/depmixS4#3]
I tried to do a likehood ratio test with `llratio()` and got a negative chi^2 value. 

So I was wondering if this line would be better that way: `llr <- -2*(llbase-llcon)`

https://github.com/depmix/depmixS4/blob/4781ab143be7c9e3e8c78f6910dac038bdb5d3c8/R/llratio.R#L15

**Comment by mspeekenbrink** [comment]
Hi @sjewo

As described in the documentation of `llratio`, the function should be called as

```
llratio(basemodel, constrainedmodel, ...)
```

The `constrainedmodel` should be a restricted version of the `basemodel` and as such, should in principle never have a higher likelihood than the `basemodel`. Therefore, `(llbase - llcon)` should be positive, and the resulting value of `llr` as well.

It might be that for particular estimates of your base and constrained model, you obtained a local optimum, in which case the obtained likelihood of the constrained model could be higher than that of the base model. Or it could be that you provided them in the wrong way (i.e. supplying the constrained model as the `basemodel` argument.

Best wishes
Maarten
